--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t node-server Dockerfile"
      - "docker tag node-server 
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - cat  /etc/os-release
      - systemctl enable docker 
      - service docker start 
      - docker --version 
      - docker images
     
version: 0.1

