--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t node-server Dockerfile"
      - "docker tag node-server sankarv/node-server:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push sankarv/node-server:latest"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - curl -fsSL https://get.docker.com -o get-docker.sh
      - sh get-docker.sh
      - docker --version 
      - docker images
      -  "docker login --username=sankarv --password=81257San."
version: 0.1

